- name: Task level variables
  hosts: local
  connection: local
  tasks:
    vars:
      COURSE: Devops
      TRAINER: Meena
  - name: Printing task level variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}"