- name: Task level variables
  hosts: local
  connection: local
  vars:
    COURSE: Devsecops
  tasks:
  - name: Printing task level variables
    vars:
      COURSE: Devops
      TRAINER: Meena
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}"