- name: Install and uninstall packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Install and uninstall packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: 'present'}
    - { name: 'nodejs', state: 'absent'}
    - { name: 'mysql', state: 'absent'}

