- name: Filters
  hosts: local
  connection: local
  vars:
    Course: Linux, Shell, Ansible
  tasks:
  - name: Filters
    ansible.builtin.debug:
      msg: "{{ Greetings | default('Good Morning')}}"
  
  - name: String to list
    ansible.builtin.debug:
      msg: "{{ Course | split(',') }}"