- name: Filters
  hosts: local
  connection: local
  vars:
    Course: Linux, Shell, Ansible
    tagsMap:
      name: Meena
      course: Devops
      duration: 4
  tasks:
  - name: Filters
    ansible.builtin.debug:
      msg: "{{ Greetings | default('Good Morning')}}"
  
  - name: String to list
    ansible.builtin.debug:
      msg: "{{ Course | split(',') }}"

  - name: Map to list
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items }}"